version: "{build}"

clone_folder: c:\gopath\src\github.com\mackerelio\go-osstat

environment:
  GOPATH: c:\gopath
  GOROOT: c:\go112-x86

install:
  - go version
  - go env

build_script:
  - go get -d -v -t ./...

test_script:
  - go test -v ./...
  - cd cmd\osstat && go build && .\osstat

deploy: false
