version: "{build}"

clone_folder: c:\gopath\src\github.com\mackerelio\go-osstat

environment:
  GOPATH: c:\gopath

install:
  - go version
  - go env
  - go get -d -v -t ./...

build_script:
  - go get -d -v -t ./...

test_script:
  - go test -v ./...
  - cd cmd\osstat
  - go install
  - osstat

deploy: false
