sudo: false

language: go

go:
  - 1.11.x

script:
  - go version
  - make all
  - cd cmd/osstat && go build && ./osstat

os:
  - linux
  - osx

env:
  - CGO_ENABLED=0 GO111MODULE=on
  - CGO_ENABLED=1 GO111MODULE=on
